# Generated by Django 4.2.1 on 2023-05-29 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0002_alter_tasklist_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='task_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='Main_App.tasklist'),
        ),
    ]
